yolo-client:
    image: ghcr.io/miguelw11/yolo-edge-api/yolo-client:latest
    container_name: yolo-client
    volumes:
      - ./images:/client/images:ro
      - ./output:/client/output
    environment:
      - API_URL=http://yolo-api:8000
    networks:
      - yolo-net
    depends_on:
      yolo-api:
        condition: service_healthy

networks:
  yolo-net:
    driver: bridge
